# Generated by Django 4.1.6 on 2023-02-12 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='User ID in telegram')),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_link', models.TextField(verbose_name='Original link')),
                ('token', models.TextField(max_length=16, verbose_name='Original link token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time of receipt')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugc.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Link',
            },
        ),
    ]
