# Generated by Django 4.1.6 on 2023-02-26 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0002_clickonlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name of profile level')),
                ('max_num_of_links', models.PositiveIntegerField(verbose_name='Maximum number of links')),
            ],
            options={
                'verbose_name': 'Profile level',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ugc.profilelevel', verbose_name='Profile level'),
        ),
    ]
