# Generated by Django 4.1.6 on 2023-02-05 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_link', models.TextField(verbose_name='Original link')),
                ('token', models.TextField(unique=True, verbose_name='Original link token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time of receipt')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Link',
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
