# Generated by Django 4.1.6 on 2023-02-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_link_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
