version: '3.7'
services:
  web:
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3307:3306'
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306  # cannot change this port to other number
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: db_shortener_link_tgbot
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass1234
      MYSQL_ROOT_PASSWORD: rootpass
    restart: always
    volumes:
      - ./db:/var/lib/mysql